# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

variables: 
  KubernetesNameSpace: dev
  imageName: 'myacr.azureecr.io\myapp'
  imageTag: $(build.id)

stages:
- stage: image build
  jobs:
  - job:
    displayName: build the docker
    steps:
    - task: DockerInstaller@0
      displayName: installing docker version on agent
      inputs:
        dockerVersion: '17.09.0-ce'
    - task: Docker@2
      inputs:
        repository: 'myapp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: $(imgeTag)
        addBaseImageData: false
- stage: deploy on kubernetes
  jobs:
    - job:
      displayName: kubernetes deployment
      steps:
      - task: Kubernetes@1
        inputs:
          connectionType: 'Azure Resource Manager'
          azureSubscriptionEndpoint: 'Pay-As-You-Go(5e9c64dc-3dac-48c5-addb-e286ad2aa905)'
          namespace: 'dev'
          command: 'apply'
          useConfigurationFile: true
          configuration: 'deployment.yml'
          secretType: 'dockerRegistry'
          containerRegistryType: 'Azure Container Registry'
          azureSubscriptionEndpointForSecrets: 'Pay-As-You-Go(5e9c64dc-3dac-48c5-addb-e286ad2aa905)'
          secretName: 'mysecret'
          forceUpdate: false


      - script: |
          echo "the deployment is running "
          kubectl rollout status deployment/my-app-depployment -n $(KubernetesNamespace)
          kubectl get svc -n $(KubernetesNamespace)


